name: CI

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MetaCall CLI
        run: wget -O - https://raw.githubusercontent.com/metacall/install/master/install.sh | sh

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: https://registry.npmjs.org

      - name: Update NPM
        run: npm install -g npm@latest

      - name: Installing Dependencies
        run: npm i

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      # TODO: Have working unit tests generated
      # - name: Run Unit Tests
      #   run: |
      #     npm run test

      - name: Run Integration Tests
        shell: bash
        run: ./test.sh

      - name: Publish
        uses: JS-DevTools/npm-publish@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          access: 'public'
          token: ${{ secrets.NPM_AUTH_TOKEN }}
